safe: true
timezone: Europe/Stockholm

sass:
    sass_dir: _scss
    style: :compressed

baseurl: /wildhart.se
live_url: http://wildhart.se
live_hostname: wildhart.se
email: info@wildhart.se
google_analytics_id: UA-21812479-8

title: Wildhart
